import { access, cp, mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
const root=resolve(import.meta.dirname,'../..'),output=resolve(root,'dist/studio'),sourceSha=process.env.NEOSMARTUI_SOURCE_SHA||process.env.GITHUB_SHA||'local-unpinned';if(sourceSha!=='local-unpinned'&&!/^[0-9a-f]{40}$/.test(sourceSha))throw new Error('Invalid source SHA: '+sourceSha);
await rm(output,{recursive:true,force:true});await mkdir(output,{recursive:true});await cp(resolve(root,'apps/studio/src'),output,{recursive:true});
const copyPath=async(path)=>{const source=resolve(root,path),destination=resolve(output,path);await mkdir(dirname(destination),{recursive:true});await cp(source,destination,{recursive:true})};
for(const path of ['packages/contracts','packages/adapters/css','packages/adapters/web/components','packages/core/component-registry.json','packages/core/components','packages/core/previews','packages/flavors','packages/themes/rivet-light','packages/themes/rivet-dark','spec/core/token-contracts.json','spec/schemas/theme.schema.json','spec/schemas/theme-resolution.schema.json','spec/schemas/resolved-token-bundle.schema.json'])await copyPath(path);
const flavorDirs=(await readdir(resolve(root,'packages/flavors'),{withFileTypes:true})).filter((entry)=>entry.isDirectory()).map((entry)=>entry.name).sort();for(const name of flavorDirs)await access(resolve(root,'packages/flavors',name,'flavor.json'));
await writeFile(resolve(output,'studio-data.json'),JSON.stringify({sourceSha,flavorPaths:flavorDirs.map((name)=>'packages/flavors/'+name+'/flavor.json'),builtInThemes:{light:'packages/themes/rivet-light',dark:'packages/themes/rivet-dark'}},null,2)+'\n');
await writeFile(resolve(output,'studio-build.json'),JSON.stringify({artifact:'studio',sourceSha,publicDeployment:false},null,2)+'\n');console.log('Built NeoSmartUI Studio → '+output+' ('+sourceSha+')');
